# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    autoupdate_schedule: monthly

exclude: ^(cmake/|3rdparty/|docs/api/doxygen-awesome.css)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.4
  hooks:
  - id: clang-format
    exclude: (.json)
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-lint
    exclude: (.py.cmake|Doxyfile.cmake)
  - id: cmake-format
    exclude: (.py.cmake|Doxyfile.cmake)
- repo: https://github.com/fsfe/reuse-tool
  rev: v3.1.0a1
  hooks:
  - id: reuse
    args: [--suppress-deprecation]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.0
  hooks:
  - id: markdownlint-cli2
    files: \.(md|mdown|markdown)$
    exclude: (docs/api/docs/license.md)
